/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/Chart/BarChart.vue')['default']
    CategoryItems: typeof import('./src/components/Category/CategoryItems.vue')['default']
    DonutChart: typeof import('./src/components/Chart/DonutChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Overview: typeof import('./src/views/Lobby/components/Overview.vue')['default']
    RecordDetail: typeof import('./src/components/RecordDetail.vue')['default']
    RecordItem: typeof import('./src/views/Record/components/RecordItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Transaction: typeof import('./src/components/Transaction.vue')['default']
  }
}
